# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eIDExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eIDExample
  pod 'libPhoneNumber-iOS'
  target 'eIDExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eIDExampleUITests' do
    # Pods for testing
  end

end
